-- Run this once in Supabase Dashboard > SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.games (
  id text primary key,
  season integer not null,
  week integer not null check (week between 1 and 22),
  away_team text not null,
  home_team text not null,
  kickoff timestamptz not null,
  away_spread numeric,
  home_spread numeric,
  completed boolean not null default false,
  winner_team text,
  updated_at timestamptz not null default now(),
  check (winner_team is null or winner_team in (away_team, home_team)),
  unique (season, week, away_team, home_team)
);

create table if not exists public.picks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  game_id text not null references public.games(id) on delete restrict,
  season integer not null,
  week integer not null,
  picked_team text not null,
  is_autopick boolean not null default false,
  submitted_at timestamptz not null default now(),
  unique (user_id, season, week)
);

alter table public.profiles enable row level security;
alter table public.games enable row level security;
alter table public.picks enable row level security;

alter table public.picks
add column if not exists is_autopick boolean not null default false;

create policy "Signed-in users can see players"
on public.profiles for select to authenticated using (true);

create policy "Signed-in users can see games"
on public.games for select to authenticated using (true);

create policy "Signed-in users can see picks"
on public.picks for select to authenticated using (true);

create policy "Players can insert their own unlocked pick"
on public.picks for insert to authenticated
with check (
  auth.uid() = user_id
  and exists (
    select 1 from public.games g
    where g.id = picks.game_id
      and g.season = picks.season
      and g.week = picks.week
      and picks.picked_team in (g.away_team, g.home_team)
      and g.kickoff > now()
      and not g.completed
  )
);

create policy "Players can update their own unlocked pick"
on public.picks for update to authenticated
using (
  auth.uid() = user_id
  and exists (
    select 1 from public.games current_game
    where current_game.id = picks.game_id
      and current_game.kickoff > now()
      and not current_game.completed
  )
)
with check (
  auth.uid() = user_id
  and exists (
    select 1 from public.games g
    where g.id = picks.game_id
      and g.season = picks.season
      and g.week = picks.week
      and picks.picked_team in (g.away_team, g.home_team)
      and g.kickoff > now()
      and not g.completed
  )
);

grant select on public.profiles, public.games, public.picks to authenticated;
grant insert, update on public.picks to authenticated;
grant usage, select on sequence public.picks_id_seq to authenticated;

-- Server-only admin operations use the secret/service-role key. RLS is bypassed
-- for this role, but PostgreSQL table and sequence privileges are still required.
grant all privileges on public.profiles, public.games, public.picks to service_role;
grant all privileges on sequence public.picks_id_seq to service_role;

-- After creating the four users in Authentication > Users, add their profiles:
-- insert into public.profiles (id, display_name)
-- select id, 'Player One' from auth.users where email = 'player1@example.com';
